kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: jenkins-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31388  # porta esposta dal service NodePort
        hostPort: 31388       # porta accessibile da macOS
        listenAddress: "192.168.56.10"  # IP host del Mac, bridge host-only
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - "192.168.56.10"
            - "localhost"
            - "127.0.0.1"

