apiVersion: v1
kind: Pod
metadata:
  name: validator
  namespace: formazione-sou
spec:
  serviceAccountName: reader
  containers:
    - name: validator
      image: python:3.9-slim
      command:
        [
          "sh", "-c",
          "pip install kubernetes && python /app/validate_deployment.py"
        ]
      volumeMounts:
        - name: script
          mountPath: /app
  volumes:
    - name: script
      configMap:
        name: validate-script
  restartPolicy: Never
