apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-chart.fullname" . }}
  labels:
    app: {{ include "flask-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "flask-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort | default 31388 }}

