apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-chart.fullname" . }}
  labels:
    app: {{ include "flask-chart.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "flask-chart.name" . }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
